/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DemoChayChu;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dungna29
 */
public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
        viDu1ChayTungChu();
        viDu2ChayTungTu();
    }

    void viDu2ChayTungTu() {
        //CNTT FPOLY SP22 -->
        Thread t2 = new Thread() {
            @Override
            public void run() {
                while (true) {
                    try {
                        String text = lbl_String2.getText();
                        String arrText[] = text.split("\\s+");
                        String tuCuoiCung = arrText[arrText.length -1];
                        text = tuCuoiCung + " ";
                        for (int i = 0; i < arrText.length -1; i++) {
                            text+= arrText[i] + " ";
                        }
                        Thread.sleep(1000);
                        lbl_String2.setText(text);
                    } catch (InterruptedException ex) {

                    }
                }
            }

        };
        t2.start();
    }

    void viDu1ChayTungChu() {
        //CNTT FPOLY --> YCNTT FPOL
        Thread t1 = new Thread() {
            @Override
            public void run() {
                while (true) {
                    try {
                        String text = lbl_String1.getText();
                        String chuCaiCuoi = String.valueOf(text.charAt(text.length() - 1));//Y
                        String chuoiMoi = chuCaiCuoi + text.substring(0, text.length() - 1);//CNTT FPOL
                        Thread.sleep(1000);
                        lbl_String1.setText(chuoiMoi);
                    } catch (InterruptedException ex) {

                    }
                }
            }

        };
        t1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_String2 = new javax.swing.JLabel();
        lbl_String1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_String2.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        lbl_String2.setForeground(new java.awt.Color(51, 0, 204));
        lbl_String2.setText("CNTT FPOLY HN");

        lbl_String1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        lbl_String1.setForeground(new java.awt.Color(51, 0, 204));
        lbl_String1.setText("CNTT FPOLY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(lbl_String2)
                .addContainerGap(222, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(lbl_String1)
                    .addContainerGap(306, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(lbl_String2)
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(lbl_String1)
                    .addContainerGap(311, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_String1;
    private javax.swing.JLabel lbl_String2;
    // End of variables declaration//GEN-END:variables
}
